version: 1

formatters:
    simple:
        format: "%(name)s - %(lineno)d -  %(message)s"

    complex:
        format: "%(asctime)s - %(name)s - %(lineno)d -  %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: complex

    file:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        backupCount: 5
        level: DEBUG
        formatter: complex
        filename : logs/scraping.log

loggers:

    scraper:
        level: INFO
        handlers: [console,file]
        propagate: yes

    __main__:   
        level: INFO
        handlers: [console,file]
        propagate: yes